### ISSUE TITLE
No inference code?

### ISSUE THREAD

**Issue by gyupro** [skuley/U2-Net-Multi-Gpus-Training#1]
Thank for your great work!.

I have a few questions to make this repo better. ( Thank you for clean code )

1. Are you planning to release pre-trained weight or dataset you used to train your model?
2. I was wondering if you are planning to release inference code, let me know if you do, I will follow-up this repo.
3. As you might know, later version of U-2-Net (DIS) has been release quite long ago. Are you also willing to make DIS repo easy project and upgrade it to the next level?

Thx in advance.

**Comment by skuley** [comment]
Thank you for your interest in my work!

1. I just updated pre-trained weight and inference code. I have trained with DUTS dataset. I am planning to train with dataset our organization collected too.
2. I updated inference code. I hope this helps! :)
3. I was working on DIS for few months. I will upload pytorch lightning version soon, but upgrading network seems pretty hard.

By, 
Sungyong Hong
