### ISSUE TITLE
Where the .pth file? I found only the .ckpt file.

### ISSUE THREAD

**Issue by yinjiaoyuan** [skuley/U2-Net-Multi-Gpus-Training#8]
Thanks.

**Comment by skuley** [comment]
Thank you for your interest!

direct link:
[u2net.pth](https://drive.google.com/u/1/uc?id=1soMzlTkKH2pl6-ZkmZRwA18OnxAzFIEK&export=download)

I found out there was a typo in ckpt file link.
I have updated!

Thank you!

**Comment by yinjiaoyuan** [comment]
Do you train it use DUTS Image Dataset?

**Comment by skuley** [comment]
Yes I did!

Everything step was same with U-2-Net except for transformation!

Thank you for noticing! I will update on readme :)
