### ISSUE TITLE
Set parameters

### ISSUE THREAD

**Issue by jkippels** [skuley/U2-Net-Multi-Gpus-Training#9]
Hi,

great work. I was looking for multi gpu training of the U2 net.

Could you help me with the meaning?

tr=train
vd=validation
im=image
gt=ground truth

Is this correct?
If I set the absolute path or relative path of: `--tr_im_path | string`
`--tr_gt_path | string` , I get an error:

```
 line 15, in __init__
    assert osp.isdir(im_root) == True, f"{im_root} is not a directory"
AssertionError:  is not a directory
```

```
--tr_im_path | string
--tr_gt_path | string
--vd_im_path | string
--vd_gt_path | string

```

**Comment by skuley** [comment]
Hi @jkippels,

Thank you for your interest!

1. Yes, those abbreviations are correct!
2. check if dataset path is correct
     I used ```os.path.isdir('dataset path')``` to check if directory is valid.

reply me back when it doesn't work!

**Comment by skuley** [comment]
I think I get why you got that error.

I think you have wrote argument wrong.

Can you write down command line in here?

**Comment by jkippels** [comment]
Hi, I now got a step further, but it doesn't start training:

`python3 train_u2net.py --batch_size 8 --min_epoch 2 --max_epoch 5 --tr_im_path "train_data/DUTS/DUTS-TR/images" --tr_gt_path "train_data/DUTS/DUTS-TR/masks" --vd_im_path "train_data/DUTS/DUTS-TR/images" --vd_gt_path "train_data/DUTS/DUTS-TR/masks" --save_weight_path "weights"`

Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
2
images : 10553
gts : 10553
images : 10553
gts : 10553
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

**Comment by skuley** [comment]
This information is just saying that you can either run training in high or medium precision.

You need to tell me detail how it doesn't start training.

ps: It will be helpful if you screenshot the error message!

Thanks.

**Comment by jkippels** [comment]
Hi,
thanks!

```

root@C.5907248:/workspace$ python3 train_u2net.py --batch_size 8 --min_epoch 2 --max_epoch 5 --tr_im_path "train_data/DUTS/DUTS-TR/images" --tr_gt_path "train_data/DUTS/DUTS-TR/masks" --vd_im_path "train_data/DUTS/DUTS-TR/images" --vd_gt_path "train_data/DUTS/DUTS-TR/masks" --save_weight_path "weights"
2

images : 10553
gts : 10553
images : 10553
gts : 10553
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:67: UserWarning: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
  warning_cache.warn(
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
2
images : 10553
gts : 10553
images : 10553
gts : 10553
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

```
After this nothing happens as output. I checked htop/nvidia-smi. CPU/GPU at 100% util and 1 GB loaded in RAM.

**Comment by skuley** [comment]
Does process end after this message? Or does it keep stays like this?

if the process doens't end, I think it might be pytorch lightning bug.

[Pytorch Lightning Tutorial](https://pytorch-lightning.readthedocs.io/en/latest/model/train_model_basic.html)
This can help you debug.

So, what you want to do is..
(replace this part [Train Model](https://pytorch-lightning.readthedocs.io/en/latest/model/train_model_basic.html#train-the-model))
```python
# model
autoencoder = LitAutoEncoder(Encoder(), Decoder())

# train model
trainer = pl.Trainer(
             devices=torch.cuda.device_count(), strategy='ddp',
             accelerator='gpu',)
trainer.fit(model=autoencoder, train_dataloaders=train_loader)
```

Please try this step and if ddp doesn't work on tutorial also, you might want to reinstall pytorch lightning again and check it's dependencies.

ps: Please tell me if it went well, because it probably means that there's an error in the code!

Thanks

**Comment by jkippels** [comment]
**Does process end after this message? Or does it keep stays like this?
if the process doens't end, I think it might be pytorch lightning bug.**

It just stays like this with nothing happening.

**Please try this step and if ddp doesn't work on tutorial also, you might want to reinstall pytorch lightning again and check it's dependencies.
ps: Please tell me if it went well, because it probably means that there's an error in the code!**

I used your tutorial code and the tutorial code worked. I see progress bars etc. / epochs.

**Comment by skuley** [comment]
I am very sorry for the inconvenience.

I will go through my code and let you know if anything went wrong!

Thanks

**Comment by skuley** [comment]
Hi @jkippels,

I have looked into my code but found nothing wrong..
![image](https://user-images.githubusercontent.com/47558730/220220100-5fb2ece5-094d-4aca-9999-fc2d558e9000.png)

As you can see above, training starts properly after sanity check.

I think you might want to check dependancies and review your code once more...

Please tell me anything after that!

Thanks.

**Comment by jkippels** [comment]
Hi,

thanks for the fast reply.
I did some tests with my code.
I noticed that the code of the repo runs for me on Nvidia A5000 GPUs.
If I try RTX 4090 it does not run.
Is there maybe some compatiblity issue?

Update: 
I also checked with 8x RTX 3090. it works. So it seems to be a problem with the 4090 series.
I double checked to be sure. Everything else is the same. Just diferent hardware.

**Comment by skuley** [comment]
If Pytorch Lightning Tutorial works on RTX 40 series, it should be fine.

If RTX 40 series doesn't work, I think it should be CUDA version compatibility issue.
I did some research and found out that CUDA 11.8 version installs on RTX 4090 but Pytorch has not yet updated compatible version.

Check your CUDA version and check your torch whether cuda is available! :)
